# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a3d1965423f9142d932b83e13928493d"
name = "commercenext-mcp-agentv2"
application_url = "https://commercenext-mcp-agent.onrender.com"
embedded = true
handle = "commercenext-mcp-agentv2"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_customers,customer_read_orders,customer_read_store_credit_account_transactions,customer_read_store_credit_accounts,unauthenticated_read_product_listings"

[auth]
redirect_urls = ["https://commercenext-mcp-agent.onrender.com/auth/callback", "https://commercenext-mcp-agent.onrender.com/auth/shopify/callback", "https://commercenext-mcp-agent.onrender.com/api/auth/callback"]
